version: "3.9"

services:
  db:
    image: postgres
    restart: always
    container_name: uno-database
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: uno
      POSTGRES_HOST: uno-database
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"

  persistence:
    image: uno-persistence:0.1.0-SNAPSHOT
    ports:
      - "8081:8081"
    stdin_open: true
    tty: true
    container_name: uno-persistence-service
    environment:
      PERSISTENCE_SERVICE_HOST: uno-persistence-service
      PERSISTENCE_SERVICE_PORT: 8081
      MYSQL_HOST: uno-database
      MYSQL_PORT: 5432
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: uno
      MYSQL_USER: postgres
      MYSQL_PASSWORD: postgres
    working_dir: /fileio
    depends_on:
      - db
    volumes:
      - ./:/fileio:xro


  core:
    image: uno-core:0.1.0-SNAPSHOT
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    container_name: uno-core-service
    depends_on:
      - persistence
    environment:
      CORE_SERVICE_HOST: uno-core-service
      CORE_SERVICE_PORT: 8080


  uno-tui:
    image: uno-tui:0.1.0-SNAPSHOT
    ports:
      - "8082:8082"
    stdin_open: true
    tty: true
    read_only: false
    container_name: uno_tui
    depends_on:
      - persistence
      - core
    environment:
      UNO_SERVICE_HOST: uno
      UNO_SERVICE_PORT: 8082
      PERSISTENCE_SERVICE_HOST: uno-persistence-service
      PERSISTENCE_SERVICE_PORT: 8081
      PERSISTENCE_SERVE_PATH: /persistence/
      CORE_SERVICE_HOST: uno-core-service
      CORE_SERVICE_PORT: 8080
      CORE_SERVICE_PATH: /controller/

  uno-gui:
    image: uno-gui:0.1.0-SNAPSHOT
    ports:
      - "8083:8083"
    stdin_open: true
    tty: true
    read_only: false
    container_name: uno_gui
    depends_on:
      - persistence
      - core
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      DISPLAY: $DISPLAY
      UNO_SERVICE_HOST: uno
      UNO_SERVICE_PORT: 8082
      PERSISTENCE_SERVICE_HOST: uno-persistence-service
      PERSISTENCE_SERVICE_PORT: 8081
      PERSISTENCE_SERVE_PATH: /persistence/
      CORE_SERVICE_HOST: uno-core-service
      CORE_SERVICE_PORT: 8080
      CORE_SERVICE_PATH: /controller/
