version: "3.9"

services:

  database:
    image: mysql:5.7
    ports:
      - "3306:3306"
    container_name: uno-database
    environment:
      MYSQL_HOST: uno-database
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: uno
      MYSQL_USER: nue
      MYSQL_PASSWORD: root

  persistence:
    image: uno-persistence:0.1.0-SNAPSHOT
    ports:
      - "8081:8081"
    stdin_open: true
    tty: true
    container_name: uno-persistence-service
    environment:
      PERSISTENCE_SERVICE_HOST: uno-persistence-service
      PERSISTENCE_SERVICE_PORT: 8081
      MYSQL_HOST: uno-database
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: uno
      MYSQL_USER: nue
      MYSQL_PASSWORD: root
    working_dir: /fileio
    volumes:
      - ./:/fileio:xro


  core:
    image: uno-core:0.1.0-SNAPSHOT
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    container_name: uno-core-service
    depends_on:
      - persistence
    environment:
      CORE_SERVICE_HOST: uno-core-service
      CORE_SERVICE_PORT: 8080


  sa-uno:
    image: uno:0.1.0-SNAPSHOT
    ports:
      - "8082:8082"
    stdin_open: true
    tty: true
    read_only: false
    container_name: uno_service
    depends_on:
      - persistence
      - core
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      DISPLAY: $DISPLAY
      UNO_SERVICE_HOST: uno
      UNO_SERVICE_PORT: 8082
      PERSISTENCE_SERVICE_HOST: uno-persistence-service
      PERSISTENCE_SERVICE_PORT: 8081
      PERSISTENCE_SERVE_PATH: /persistence/
      CORE_SERVICE_HOST: uno-core-service
      CORE_SERVICE_PORT: 8080
      CORE_SERVICE_PATH: /controller/
