version: "3.9"

services:

  mongo-uno:
    image: mongo
    restart: always
    container_name: mongo-uno
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGI_INITDB_DATABASE: uno

  db:
    image: postgres
    restart: always
    container_name: uno-database
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: uno
      POSTGRES_HOST: uno-database
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"

  persistence:
    image: uno-persistence:1.0
    ports:
      - "8081:8081"
    stdin_open: true
    tty: true
    container_name: uno-persistence-service
    environment:
      PERSISTENCE_SERVICE_HOST: uno-persistence-service
      PERSISTENCE_SERVICE_PORT: 8081
      MYSQL_HOST: uno-database
      MYSQL_PORT: 5432
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: uno
      MYSQL_USER: postgres
      MYSQL_PASSWORD: postgres
      MONGO_HOST: mongo-uno
      MONGO_PORT: 27017
      MONGO_ROOT_USERNAME: root
      MONGO__ROOT_PASSWORD: mongo
    working_dir: /fileio
    depends_on:
      - db
    volumes:
      - ./:/fileio:xro


  core:
    image: uno-core:1.0
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    container_name: uno-core-service
    depends_on:
      - persistence
    environment:
      CORE_SERVICE_HOST: uno-core-service
      CORE_SERVICE_PORT: 8080


  uno-tui:
    image: uno-tui:1.0
    ports:
      - "8082:8082"
    stdin_open: true
    tty: true
    read_only: false
    container_name: uno_tui
    depends_on:
      - persistence
      - core
    environment:
      UNO_SERVICE_HOST: uno
      UNO_SERVICE_PORT: 8082
      PERSISTENCE_SERVICE_HOST: uno-persistence-service
      PERSISTENCE_SERVICE_PORT: 8081
      PERSISTENCE_SERVE_PATH: /persistence/
      CORE_SERVICE_HOST: uno-core-service
      CORE_SERVICE_PORT: 8080
      CORE_SERVICE_PATH: /controller/

  uno-gui:
    image: uno-gui:1.0
    ports:
      - "8083:8083"
    container_name: uno_gui
    depends_on:
      - persistence
      - core
    network_mode: "host"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=host.docker.internal:0.0
      - UNO_SERVICE_HOST=uno
      - UNO_SERVICE_PORT=8082
      - PERSISTENCE_SERVICE_HOST=uno-persistence-service
      - PERSISTENCE_SERVICE_PORT=8081
      - PERSISTENCE_SERVE_PATH=/persistence/
      - CORE_SERVICE_HOST=uno-core-service
      - CORE_SERVICE_PORT=8080
      - CORE_SERVICE_PATH=/controller/
