# TODO Fix pipeline, integrate tests - new tests
name: Scala CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: compile
      run: sbt compile


    
    
